Programacion/Models/Empresa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Tipo { get; set; }
    }
}

Programacion/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Programacion.Models;

namespace Programacion.Controllers
{
    public class EmpresaController : Controller
    {
        private MERInventarioContainer db = new MERInventarioContainer();

        // GET: /Empresa/
        public ActionResult Index()
        {
            return View(db.EmpresaSet.ToList());
        }

        // GET: /Empresa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.EmpresaSet.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // GET: /Empresa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Empresa/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Nombre,Direccion,Telefono,Email,Ciudad,Departamento,Tipo")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.EmpresaSet.Add(empresa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(empresa);
        }

        // GET: /Empresa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.EmpresaSet.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: /Empresa/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Nombre,Direccion,Telefono,Email,Ciudad,Departamento,Tipo")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empresa);
        }

        // GET: /Empresa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.EmpresaSet.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: /Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empresa empresa = db.EmpresaSet.Find(id);
            db.EmpresaSet.Remove(empresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Programacion/Views/Empresa/Create.cshtml
@model Programacion.Models.Empresa

@{
    ViewBag.Title = "Create";
}

<div id="contact" class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="section-title">REGISTRAR EMPRESA</h1>
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->
        @using (Html.BeginForm())
        
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion)
                @Html.ValidationMessageFor(model => model.Direccion)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono)
                @Html.ValidationMessageFor(model => model.Telefono)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ciudad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad)
                @Html.ValidationMessageFor(model => model.Ciudad)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departamento)
                @Html.ValidationMessageFor(model => model.Departamento)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo)
                @Html.ValidationMessageFor(model => model.Tipo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="REGISTRAR" class="button" />
            </div>
        </div>
    </div>
        }

        <div class="form-group" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink(" VER EMPRESA", "Index")
            </div>
        </div>

    </div>
 </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Programacion/Views/Empresa/Delete.cshtml
@model Programacion.Models.Empresa

@{
    ViewBag.Title = "Delete";
}

<div id="contact" class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="section-title">ELIMINAR EMPRESA</h1>
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->
        <div>
            <div class="form-horizontal" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Direccion)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Direccion)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Telefono)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Telefono)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Ciudad)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Ciudad)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Departamento)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Departamento)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tipo)
                    </dd>

                </dl>
            </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
        <input type="submit" value="ELIMINAR" class="button" /> |
        @Html.ActionLink("VOLVER A LA LISTA", "Index")
    </div>
                }
            </div>
    </div>
 </div>

Programacion/Views/Empresa/Details.cshtml
@model Programacion.Models.Empresa

@{
    ViewBag.Title = "Details";
}

<div id="contact" class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="section-title">DETALLE EMPRESA</h1>
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->

        <div class="form-group">
            <br />
            <div class="col-md-offset-2 col-md-10" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Nombre)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Direccion)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Direccion)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Telefono)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Telefono)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Ciudad)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Ciudad)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Departamento)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Departamento)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Tipo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Tipo)
                    </dd>

                </dl>
            </div>
           </div>
        <br />
        <br />
        <div class="form-group" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("ACTUALIZAR EMPRESA", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("VER EMPRESA", "Index")
            </div>
        </div>
     </div>
  </div>

Programacion/Views/Empresa/Edit.cshtml
@model Programacion.Models.Empresa

@{
    ViewBag.Title = "Edit";
}

<div id="contact" class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="section-title">ACTUALIZAR EMPRESA</h1>
            </div> <!-- /.col-md-12 -->
        </div> <!-- /.row -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <form method="post" style="background-color: #D8F6CE; width: 2000px; margin: 0 auto">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Nombre)
                    @*@Html.ValidationMessageFor(model => model.Nombre)*@
                </td>



                <td>
                    @Html.LabelFor(model => model.Direccion, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Direccion)
                    @*@Html.ValidationMessageFor(model => model.Direccion)*@
                </td>



                <td>
                    @Html.LabelFor(model => model.Telefono, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Telefono)
                    @*@Html.ValidationMessageFor(model => model.Telefono)*@
                </td>
            </tr>


            <tr>
                <td>
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Email)
                    @*@Html.ValidationMessageFor(model => model.Email)*@
                </td>



                <td>
                    @Html.LabelFor(model => model.Ciudad, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Ciudad)
                    @*@Html.ValidationMessageFor(model => model.Ciudad)*@
                </td>



                <td>
                    @Html.LabelFor(model => model.Tipo, new { @class = "control-label col-md-2" }) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    @Html.EditorFor(model => model.Tipo)
                    @*@Html.ValidationMessageFor(model => model.Tipo)*@
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.Departamento, new { @class = "control-label col-md-2" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.EditorFor(model => model.Departamento)
                    @*@Html.ValidationMessageFor(model => model.Departamento)*@
                </td>
            </tr>
        </table>


          <div class="form-group" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
              <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ACTUALIZAR" class="button" />
                  @Html.ActionLink(" VOLVER A LA LISTA", "Index")
              </div>
          </div>
    </form>
        }

        
     </div>
  </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Programacion/Views/Empresa/Index.cshtml
@model IEnumerable<Programacion.Models.Empresa>

@{
    ViewBag.Title = "Index";
}

<div id="contact" class="content-section">
    <div class="container">
        <br />
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="section-title">LISTA DE EMPRESA</h1>
            </div> <!-- /.col-md-12 -->
        <br />
        <br />
        <br />
        <br />
        </div> <!-- /.row -->

       @*<p>@Html.ActionLink("REGISTRAR EMPRESA", "Index", "Empresa")</p>*@
@foreach (var item in Model)
            {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Direccion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefono)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ciudad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Departamento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th></th>
            </tr>

           
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ciudad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Departamento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipo)
                    </td>
                   
                </tr>
            

        </table>
    <br />
    <br />
       <div class="form-group" style="background-color: #D8F6CE; width: 500px; margin: 0 auto">
            <div class="col-md-offset-2 col-md-10">
              @Html.ActionLink("VER DETALLE DE LA EMPRESA", "Details", new { id = item.Id }) 
            </div>
        </div>
            }
        <br />
        <br />
        
    </div>
 </div>